export const combatOneHint = "The first monster you will face has a stealth trait. A heavy attack might be too slow for this one.";
export const combatTwoHint = "The second monster you will face has a charged attack trait that deals heavy damage. Defending the turn after it charges can reduce the damage."

export const combatThreeHint = "The third and final monster you will face has a large amount of health along with a huge defense bonus while inside it's shell. However, it also has is a bit of an anger problem. If you were to taunt it enough, it may come out of it's shell in a rage. Luring the monster out of it's shell would significantly drop it's defense."
export const elfIntroScene = "You are a Elf from the realm of Niflheim. Your people have ecountered a new form of disease unbeknowst to your people. Over 70% of your people have fallen victim to this pernicious disease with no hope of a cure. You are a royal knight who specialsed in medicine and potions. You were born a mixed blood who's father was orignally from the realm of Mythralis. Due to this the disease has not effected you yet. On the order of the King you are repatriated back to Mythralis in the hopes of finding a cure. Upon arriving in Mythralis you become decide to take shelter in the forrest. Upon making a tent you notice a faint voice in the hole of a large tree centralised in the forrest. You decide to enter the hole and fall into a tomb where an ancient power hid away starts to call your name. You follow the voice and enter a room dimmly lit with the surrounding area covered in different shapes and boulder sizes. Upon closer in spection the ancient power becomes fienter and a new voice emerges commanding you to leave. You try to find the source of the voice however the speeds and distance of the voice is just a foot away from you each time. Finally locating the source of the voice by destroying a boulder that was used for cover a goblin scout by the name of Fretral who calls himself the guardian of the power and only those worthy of besting him in combat are able to proceed."
export const  dwarfIntroScene ="You are a Dwarf from the realm of Niðavellir. Your people are summoned by the chief diety Moradin with the task of building an armour with an immortal resilience to enter and conquer the realm of Zrur Ozdrudth which are home to the Orcs. All previous attempts to penetrate the realm have been futile with the army suffering great losses and the defense armour being shattered instantly upon entering Zrur Ozdrudth. The final hope resides in your fate as you embark on a journey to enter the unknown lands of Mythralis. You begin to find Ores almost as strong as the ones from your realm in abundance however this is not enough to satisfy your desire. You begin to mine in a underground cave when the floor below you disintergrets and you find yourself in an ancient tomb. Upon closer inspection you realise there could be great treasure which lies ahead as you find yourself in the depths of this tomb. Upon entering a small reserve deposit there is different boulder shapes and sizes where there is small chatter that leaves you restless. You quickly draw for your sword and cut one of the boulders to find a cover scout goblin who goes by the name of Fretral Fretral who calls himself the guardian of the power and only those worthy of besting him in combat are able to proceed." 
export const humanIntroScene = "You are a archaeologist who is fascinated by the unknown exploration of different areas. Your specialty is underground exploriation. Upon inspecting different areas around the world you realise there is over 50% of an area of underground system unexplored. You embark a journey where you travel to Paris France. Upon arriving you head down under the bright city lights into the sewage system. Upon arriving you find a hidden entrance to the catacombs which has the same tunnels and paths of previous routes you are well knowledged in. Using the information you have you travel alone deeper into the catacombs when you realise the path has rerouted and changed until you find yourself going in a circle. In a panic you then start to sprint and lose your sense of direction when you finally see a light at the end of the tunnel. Upon opening the door you find yourself in a mysterious land known as Mythralis. All your previous findings had only hypothesised a place like this to exist and here you are becoming the first person to factualise the theory. You head down into a similar tomb system to the one you had recently went through in paris when you find a strange passage opening. Curiosity gets the better of you again and you decide to head down the path where you find a room full of boulders. you hear a faint voice in the room beside you when you finally see a  a goblin scout by the name of Fretral who calls himself the guardian of the power and only those worthy of besting him in combat are able to proceed."
export const wizardIntroScene = "You are wizard from the realm of Aeythaer. Everyone in your realm is all powerful and has different spells and knowledge that far surpasses you. With the whole realm in knowledge of this they are unable to say anything other than disgruntled sounds and backbiting. This is due to your father being the all powerful Zephyrwick Spellflinger who is the immortal founder of the realm. The tension of the realm rises and they force and ultimatum upon your father by having a trial by combat in order to prove your worth. With this knowledge your father exhiles you from the realm and speaks not a word other than failure. You leave the realm disgruntled and disheartened only to find a map in your backpack left by your father in there is instructions to travel to Mythralis in search for the tears of the world tree. You decide to embark on the journey and find a path which has your fathers spells on the floor. You being the heir with similar but lower level magic it is just enough for the spell recognise you. You become descending into the floor confused you begin to survey your surroundings. You find a tomb full of boulders with a voice telling you to leave at once. Then appears a cover scout goblin who goes by the name of Fretral Fretral who calls himself the guardian of the power and only those worthy of besting him in combat are able to proceed.   "


export const shelldonTauntedOne = "Shelldon raises an eyebrow, and a look of agitation grows.";
export const shelldonTauntedTwo = "I think that hit a nerve, mild agitation evolves to a look of seething bloodlust";
export const shelldonTauntedThree = "Pushed past the brink of tolerance, Shelldon clumsily comes steaming out of it's shell, blabbering a rapid-fire torrent of unintelligible yet piercing remarks.";

